In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
import datetime

In [2]:
dates = pd.date_range(start='7/1/2016', end='11/14/2016', freq='D', normalize=True)
s = pd.Series((dates[i].dayofweek for i in range(len(dates))), index=dates)

In [3]:
s.name = 'daytype'

In [4]:
day_type_df = s.apply(lambda day: day + 1)

In [5]:
#1是第一个工作日
#2是第二个工作日
#3是第三个工作日 
#4是第四个工作日 
#5是工作日最后一天 
#6是假期第一天 
#7是假期最后一天
#8是假期中，

In [8]:
#假日修正
day_type_df['2016-09-14'] = 5

day_type_df['2016-09-15'] = 6
day_type_df['2016-09-16'] = 8
day_type_df['2016-09-17'] = 7
day_type_df['2016-09-18'] = 1

day_type_df['2016-10-02'] = 8
day_type_df['2016-10-03'] = 8
day_type_df['2016-10-04'] = 8
day_type_df['2016-10-05'] = 8
day_type_df['2016-10-06'] = 8
day_type_df['2016-10-07'] = 7
day_type_df['2016-10-08'] = 1
day_type_df['2016-10-09'] = 1

In [9]:
day_type_df = day_type_df.to_frame()

In [10]:
day_type_df

            daytype
2016-07-01        5
2016-07-02        6
2016-07-03        7
2016-07-04        1
2016-07-05        2
2016-07-06        3
2016-07-07        4
2016-07-08        5
2016-07-09        6
2016-07-10        7
2016-07-11        1
2016-07-12        2
2016-07-13        3
2016-07-14        4
2016-07-15        5
2016-07-16        6
2016-07-17        7
2016-07-18        1
2016-07-19        2
2016-07-20        3
2016-07-21        4
2016-07-22        5
2016-07-23        6
2016-07-24        7
2016-07-25        1
2016-07-26        2
2016-07-27        3
2016-07-28        4
2016-07-29        5
2016-07-30        6
...             ...
2016-10-16        7
2016-10-17        1
2016-10-18        2
2016-10-19        3
2016-10-20        4
2016-10-21        5
2016-10-22        6
2016-10-23        7
2016-10-24        1
2016-10-25        2
2016-10-26        3
2016-10-27        4
2016-10-28        5
2016-10-29        6
2016-10-30        7
2016-10-31        1
2016-11-01        2
2016-11-02        3
2016-11-03        4
2016-11-04        5
2016-11-05        6
2016-11-06        7
2016-11-07        1
2016-11-08        2
2016-11-09        3
2016-11-10        4
2016-11-11        5
2016-11-12        6
2016-11-13        7
2016-11-14        1

[137 rows x 1 columns]

In [11]:
day_type_df.to_csv("./data/dataset/dataset/week_circle_calendar.txt", sep='\t', index=True, encoding='UTF-8')